version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/goforms"
    schedule:
      interval: weekly

  - package-ecosystem: "composer"
    directory: "/goformx-laravel"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/goformx-laravel"
    schedule:
      interval: weekly

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
